include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - build/**
    - lib/generated/**

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Essential rules for better code quality
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - use_key_in_widget_constructors
    - require_trailing_commas
    - sort_child_properties_last
    - always_declare_return_types
    - annotate_overrides
    - avoid_unnecessary_containers
    - prefer_single_quotes
    - lines_longer_than_80_chars
